ClusterName=docker_cluster
SlurmctldHost=slurmctld
AuthType=auth/munge

# Hardware & Process Tracking Fixes
SlurmdParameters=config_overrides
ProctrackType=proctrack/pgid

# Node Definitions
NodeName=node[01-02] NodeAddr=node[01-02] CPUs=1 State=UNKNOWN
PartitionName=debug Nodes=node[01-02] Default=YES MaxTime=INFINITE State=UP

# Operational Settings
SlurmUser=slurm
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
