services:
  slurmctld:
    build: .
    container_name: slurmctld
    hostname: slurmctld
    command: slurmctld
    volumes:
      - ./config/slurm.conf:/etc/slurm/slurm.conf
      - .:/home/slurm
    working_dir: /home/slurm
    networks:
      - slurmnet

  node:
    build: .
    command: slurmd
    volumes:
      - ./config/slurm.conf:/etc/slurm/slurm.conf
      - .:/home/slurm
    working_dir: /home/slurm
    networks:
      - slurmnet
    depends_on:
      - slurmctld

networks:
  slurmnet:
    driver: bridge
